djangoSecretKey: ENC[AES256_GCM,data:RkqjUm+nZdo4aNr1p58SwYLKU+Md8m8hvWHMGM1f2oDh0k0+7hO51Jh3cRHzC2jR5fI=,iv:kZBr0owTON1YEX0YTHmHMe2P4GXtwFMEO5rfHGpAkzM=,tag:ZShPIQfoC/u8hjxWLrihpQ==,type:str]
oidc:
    clientId: ENC[AES256_GCM,data:4lNTVeWI7Pm3V6VWFa10a0sL51Do022v9lCtJbPYbSEzv+GA,iv:YXtOZmDJseOsduMKyAL3UYvJCS22MS+qDRv34rRH45E=,tag:/Lc1VSC4mxqTopX3N+YWEw==,type:str]
    clientSecret: ENC[AES256_GCM,data:FRnCuBMIYyOeWaJwj5RvYseLTvYq43x1+AErD832tpgOc6K3GHjcYF9eKDEc2fOo7SpxHvk/Z6brm1gs1cUFrg==,iv:YgO0CEnLL6MCULOR9pfWCD7lJjpWO5ybnU4lD4MbkV8=,tag:7W7yacyO4Dofp0r0KB3Knw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15fyxdwmg5mvldtqqus87xspuws2u0cpvwheehrtvkexj4tnsqqysw6re2x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZGdzdFF1VmFmNk9DT21Q
            Q3EwZXRtTkRnY25FbVVFZWxiQWlJRGtTdW1rCkVzU3M1YjJCYXBVckRHM1JsZFM1
            OFFBUk11eDBhb0djVEZNV1pYbXlYYmsKLS0tIG9CNXJHUHZaSXBMT3R6M2dVRUtr
            ajZ1R1NGZ0NXNkFsVmlDQTM1MTBUOXMKwEnN6Biu0D6hyPBl+yF9xn091YVsNiYz
            Xn8/lsij3f972H9G+be3p+HlxBczUyyX6dhXR+TNlLj88PmB3QbtAQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16hnlml8yv4ynwy0seer57g8qww075crd0g7nsundz3pj4wk7m3vqftszg7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbkV0RHgwckdadG5NQUJC
            TmIybmQ4NUFINWZkSW11MkxvY0dRVnMwUEN3CkNrL2szZWZmY3ptZkh3UVljSmVW
            R3VCZENsRktiT1pVWGEvWk04Q2FmSDQKLS0tIGE3eDNPOUpLa3FmeFhRRlQ3b3g3
            N0QzdjVFNkZwRkljYmpGdHVhbDhYVFUKRJwR3I6od2si5xB8K31Y2INfpmB0DTQD
            un2srlg0iRcOVls55R9NnuS3wmpazWdTDHIbUmzQ+L/xTrcwH88XlQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1plkp8td6zzfcavjusmsfrlk54t9vn8jjxm8zaz7cmnr7kzl2nfnsd54hwg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIM0x6M1lxMDRuYVVwV0Jo
            MlVPUjk3U2d2dE1LS1BESnhkZGFzVEwzU2xZCkVpanpFUVFNNU1CRjJnMXpzTmRZ
            R0lUbStnQmJOWFpmdmZuV2EwclRHT0kKLS0tIHpJb1E0c2k3Ujk3RlFQejJiQ3k2
            SGhYckRFR3g2a2ZxdmlVd2JFTUZRQ1kKvdfl6yPXOiJuOnLeMB5y8SLJ9ih5qlLz
            10AOiluGgCO56qD8BZC1U/JUGiquTAV5Pz2xcveS+4LOrs41z+ijzg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12g6f5fse25tgrwweleh4jls3qs52hey2edh759smulwmk5lnzadslu2cp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUFg4Yk1uVmFYeE91MkNS
            S2JMNkNGVkhwMFlzdmlXY0ZyODFGK2xEWVFjCmhFbDMrM1hjK1picHdPNkU4ZGsx
            MCt6cGVQdloyUlhpbkRzL2N3dXpXRm8KLS0tIDhydFBQSFRCUi9UdWNVaFRJMm40
            MEt6ZVdtSnZidnlwczFaNlJ3OGh0cUEKibXyzHHSFZ4eTvkb7Hiu7gk+f4X6ErEA
            FjZ0ULLDOI7qg809c+ZWrD+KD3/7CPce8cUNuLJhhDEza2wtnyClTA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hnhuzj96ktkhpyygvmz0x9h8mfvssz7ss6emmukags644mdhf4msajk93r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0STdCSHVXNDdRVlR4RUJu
            VkFDa2l0V2hkamdoTnhTOSt4V1YvRUxKVldVCjNyQXh3NjZJVmlQVXZkTVQ1WW05
            a0VpYTNOTmRFRW1waG92ejVHNmVTdEkKLS0tIDhUNk1BZm5xR1FiSk10RXRNSGg3
            ZlJyY3JaalMrTjQ4b3o2OXIybVBzcVkKaNOzvmq4wEMzTPYK2TpEYXKajXQ8lExy
            ZzsHPHHmKfgVvgIX7eDzDyGy23c/bqkd8bJ11eJT4rYUMeMP6Y2HnQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tl80n23wq6zxegupwn70ew0yp225ua5v4dk800x7g2w6pvlxz46qk592pa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUmlSUEkrbVJ1amRVL3NE
            YjNFQnVadW0rSEg5WEdVNjBJRVZpZjVzSEhnCmZVOVZ2UGh5SERFZDVGUy9DdkNy
            cmNVT2hTTkhISlc5SU9kaCtQZnh1NHcKLS0tIHpFR1Btc2tsbm5PbnpUZGZ1dm5R
            b1lqUGI4dHZJdDFxT3R6ZmlSZFBnMG8KWWxmfxvB0jWB8qhjXUG6rL0lqyxXszgP
            D4Lqyb3ZBOuJ82EHFZCqVLwhtJCv2bp91HmwBgKI2bC4J9eU5/0oug==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age175v7g8tmv7gur6xaqvzzwe4h4ttfqpqk3fqcllx3uv67alc3pexsk2w6mt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNDdRZ0w5Wnh4WXBWOXdS
            NXlZdUFEU2FKY25DNlAyTllwT25UTTZ5dVVFCnlHa1pYeVNhemEyOGxRWGJ5bTdo
            dHhZVUNHWHd4Q0xYdHpZcVR4Uk1XRUkKLS0tIFY5aHpxWUJUVEpLS1lrK0ZGTEpv
            UXo0YnkvOVZxNUhTUlVVdDBJUUoxRTAKrLDZeDLwV5HcC5nFRQdgd/1j+YBGO/Ky
            vO8OGQDq3PBlYaukO+ztYFcILCge7z/DrUnHcz0WZ+r3GKJ2/eFq4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-16T15:01:09Z"
    mac: ENC[AES256_GCM,data:L4QTP5A9CcCWniR2+JedN5qOtmchBc/sfDk0dg/Y9BK8GIvNCStuGR3be2ypzaOSu0LPXap2B4gH4qqmsY2OLY2rfD7LRdGyfHkEy7YpFksT+JUrSsdvZnTxPPwGLSIeSQxpR0gCUKKlu7pWxgfCRJiCd0CH8nHdr/PLB2HoHuI=,iv:HhPsRAV4T01mOqB7uUpQLNNveyvhIWQGmcwGZgF1ZZA=,tag:9/L7SQ8v06cNbtZoB6bjew==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
