djangoSecretKey: ENC[AES256_GCM,data:QEndrhW5eHK4ZYmFF0baNh5jwHIFN3dQDSZ8VO3MQKyp9ldwifB3f0E1ar7Eta7ppQc=,iv:i0DWd5D+nsF6q5UzpQol3X14pEKcXoM+tRB1ybt61Rs=,tag:57+twHtnABFp82I4skojmg==,type:str]
oidc:
    clientId: ENC[AES256_GCM,data:Geggz7WIJRleIjeLSdr64g4cdwTP9hoe/DKu+C1gQUtHKsZj,iv:ULjCaCBfdHtdOcGlvcR0PKvDiaZByTkzMuwVlyr5z/0=,tag:+qAKrORmaDDwh9es9VHNow==,type:str]
    clientSecret: ENC[AES256_GCM,data:FzbtnihFbevvd4CBHfhVfUJgJp06fACRO+cFxpipdwEgrI8uJ4tHVbAxbUTyj2fP8FtKXzRIVIA+cVCTt1fTxg==,iv:bzko7GBW5F4HJ5iWSAo+VEGjlDtgq8DKreEKV7T0c8Q=,tag:M7uUumIBzj+0LVp9ijiEtg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15fyxdwmg5mvldtqqus87xspuws2u0cpvwheehrtvkexj4tnsqqysw6re2x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNW9IK0hJeXAvYlN4aUZF
            ckJiMmxWYk1jQll0cDJPcHZVanc1allqdldnCnl2cEFXSnB0ZkJhYVBVOUZ4U1d4
            SHRxTXAvVmg0OUc3SVdzeThXellHNDAKLS0tIEh1NHBlRFdXSmVpejBYKzhDdFFk
            WVlVVDg4TFVNNU8wSjJ4bzB2VGRkQXMKqOeeUMlJSgG/o8Sim0gvb93tNvfJoysB
            dZKmK21i5A9y1mnBVQ1GBi3dsJx1CjDL/vkt96R61hvEOYd+YR3IaA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16hnlml8yv4ynwy0seer57g8qww075crd0g7nsundz3pj4wk7m3vqftszg7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VGw0SWcycUhMRzF2eDNt
            QnRIbXJ6M0sydFk2NnNleHRyWGlDS3FoR1g0ClRxbTBGSlVUcDdaS2FOTGRLRzhQ
            dUFtTWI5Y0VhYVBGNkp4eFJBajFrK3cKLS0tIG1pdGhpOHZSOVBrSS9NNE9vTFA0
            MnNCa29FWXpabVdBTytLMWFQRkRFWDAK6amM7pir8r8hDB+Bv9Qr7PKZhrvMTSz0
            R21dq3caa3jgotrUQ4zva2AxS53+CNx1M0nGXQWCOumFPXRcWO6Q9g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1plkp8td6zzfcavjusmsfrlk54t9vn8jjxm8zaz7cmnr7kzl2nfnsd54hwg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwK1Y5U1JFckNQSXQ1ZzlV
            ajEvRWlzZzdnanpCQ01lRmIxTFB3M1hGOVMwCmRoSkhKSjhHcjV3M20zN1Y1bjZN
            NXY4bzZxbllLLzN0dU5DRkgzdTZGejgKLS0tIGlkc21XNXI1MnRDUkwzN0kycGVX
            eWZYK01uS1poSTB1SGtHbGp1VENRNjgKI7grZkTKmin/mp6yVRcT+SHdvz88t+3o
            4Fs6bNSimNWkCEwQgQ+u4jsFTD9+SrxGnVOUpSYqjQPIHN2Y4P/3+g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12g6f5fse25tgrwweleh4jls3qs52hey2edh759smulwmk5lnzadslu2cp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRFhsTldHTmQrbHptKzJq
            TWtLMXNGVElkRlBhcVBjT2JwV2djMVRBRlRrClJBdVdHZFBQTUZRTitHbExGQTRp
            cXZSR3p2ZDNEZzJHTk11b1NnUGtsNlUKLS0tIG9kRHQvS1RNeGZLc1R1MEkveUZv
            a2NMNFZIeUpFSFNZaHpSRGZ1MEYwSWsKHX60Mdd/vquJvHu35E2h3WBXo471ffxa
            V6C4MHl3BZ+3TVBn7z29n60owvR5lIJnfUdf6SwCEt5H+PMEvvi+6Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hnhuzj96ktkhpyygvmz0x9h8mfvssz7ss6emmukags644mdhf4msajk93r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dk1TUnhqdHlzVTZUa1BQ
            NGFXcEtIOWlDYlErSzFJZlR5aDYrak9kd1VVCnNTYVVUbTIzQjBIZi9OanlYQ0Ni
            Z2hkenI3S01HK2Jwdi9ReWNBUHpFVFkKLS0tIFNWQW9DWitNc3N4QWM4YjRQR2FT
            bzBqSmdDem9YQTdtNkxIMzQ4cld0UVUKmLRJP6pqfWHNqWHTcDowa8kIJczVJI4o
            Eqh+IzMcafkQwA6je5PzXczTYEgbnPnI4yMedVrw5yqox4J2kZQQzA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tl80n23wq6zxegupwn70ew0yp225ua5v4dk800x7g2w6pvlxz46qk592pa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTa0VWMmpZWUF5NnpBQkEr
            bGlJOWM0NVhTbzZnbm5CYnJGOE1VYzJJakdNCk5SYWloVXdhM3JmSG1WdVpROGxF
            b0JGMUk0SjFhWHliSWlEamYxOG9BS1UKLS0tIFNVUHVBT3ZERUVPOU04eFd3Ukxw
            cmwzQVBUa0FRNjFiamlrQzNvbkk4b1UK/5K542faATiH/MCMSRPPhw4sJfGwfS4k
            lwE90hNk2Ml53uKVewYuT/iTKpTgrb0LuYY2rwK0DCNMws9Q6TWCCw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age175v7g8tmv7gur6xaqvzzwe4h4ttfqpqk3fqcllx3uv67alc3pexsk2w6mt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpSUtBWDYwMWNFQTdmbkZq
            d0ExOXY5TWx5aHl2N1M4M0EwaUdoWWFWK2lrCmtyRGszRlQxRHp6WmkvL0o0ZFVO
            V0RvSXdETUxTbUJNZDNXbEVjcUFwZGMKLS0tIEVhMWlCNVZ2M3l1ZjNhYW9GbFA0
            M0w4RDg2cHdMWktycWlOdDh6azNNUTgKm9XujJPpsVC+au/oJgx4VQbMlkYqmxCw
            VisIQOvwOmbEZk/9MIQQjwpyPIzY3H5x2uSOjra0eyO/21hwua+HJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-17T10:13:28Z"
    mac: ENC[AES256_GCM,data:CzHevUPxeOJUZ75HJpzdXqnMGTLdjhyM3NJfOdJjzHKaooPSBTHyc2vRIee35pVmWfKOA84lZ27OWQVIrbYRX6J2C/vmTA20uFRYBXn1fGxDdnI/3k6Kn/Cg+dTFI8s0hURZX7SoeLjFyhc0zbsfktkgG9cdqXJLd2h7kHQLESA=,iv:nAJhN0hTuCjCpGTMf+UqJu4Tvj/rLjGvdZYE6bxE33Q=,tag:2BWtA8fDhNXD22umdmFMwQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
