"""
Django settings for project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import json
import os
from socket import gethostbyname, gethostname

from django.utils.translation import gettext_lazy as _

import sentry_sdk
from configurations import Configuration, values
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.logging import ignore_logger

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join("/", "data")


def get_release():
    """
    Get the current release of the application

    By release, we mean the release from the version.json file à la Mozilla [1]
    (if any). If this file has not been found, it defaults to "NA".

    [1]
    https://github.com/mozilla-services/Dockerflow/blob/master/docs/version_object.md
    """
    # Try to get the current release from the version.json file generated by the
    # CI during the Docker image build
    try:
        with open(os.path.join(BASE_DIR, "version.json"), encoding="utf8") as version:
            return json.load(version)["version"]
    except FileNotFoundError:
        return "NA"  # Default: not available


class Base(Configuration):
    """
    This is the base configuration every configuration (aka environment) should inherit from. It
    is recommended to configure third-party applications by creating a configuration mixins in
    ./configurations and compose the Base configuration with those mixins.

    It depends on an environment variable that SHOULD be defined:

    * DJANGO_SECRET_KEY

    You may also want to override default configuration by setting the following environment
    variables:

    * DJANGO_SENTRY_DSN
    * DB_NAME
    * DB_HOST
    * DB_PASSWORD
    * DB_USER
    """

    DEBUG = False
    USE_SWAGGER = False

    API_VERSION = "v1.0"

    # Security
    ALLOWED_HOSTS = values.ListValue([])
    SECRET_KEY = values.Value(None)

    # Application definition
    ROOT_URLCONF = "main.urls"
    WSGI_APPLICATION = "main.wsgi.application"

    # Database
    DATABASES = {
        "default": {
            "ENGINE": values.Value(
                "django.db.backends.postgresql_psycopg2",
                environ_name="DB_ENGINE",
                environ_prefix=None,
            ),
            "NAME": values.Value("main", environ_name="DB_NAME", environ_prefix=None),
            "USER": values.Value("dinum", environ_name="DB_USER", environ_prefix=None),
            "PASSWORD": values.Value(
                "pass", environ_name="DB_PASSWORD", environ_prefix=None
            ),
            "HOST": values.Value(
                "localhost", environ_name="DB_HOST", environ_prefix=None
            ),
            "PORT": values.Value(5432, environ_name="DB_PORT", environ_prefix=None),
        }
    }
    DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

    # Static files (CSS, JavaScript, Images)
    STATIC_URL = "/static/"
    STATIC_ROOT = os.path.join(DATA_DIR, "static")
    MEDIA_URL = "/media/"
    MEDIA_ROOT = os.path.join(DATA_DIR, "media")

    SITE_ID = 1

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
        },
        "staticfiles": {
            "BACKEND": values.Value(
                "whitenoise.storage.CompressedManifestStaticFilesStorage",
                environ_name="STORAGES_STATICFILES_BACKEND",
            ),
        },
    }

    # App
    APP_EMAIL_FORCE_TO = values.Value(
        environ_name="APP_EMAIL_FORCE_TO", environ_prefix=None
    )
    APP_WORK_DIR = values.Value(environ_name="APP_WORK_DIR", environ_prefix=None)

    # Media
    AWS_S3_ENDPOINT_URL = values.Value(
        environ_name="AWS_S3_ENDPOINT_URL", environ_prefix=None
    )
    AWS_S3_DOWNLOAD_URL = values.Value(
        environ_name="AWS_S3_DOWNLOAD_URL", environ_prefix=None
    )
    AWS_S3_ACCESS_KEY_ID = values.Value(
        environ_name="AWS_S3_ACCESS_KEY_ID", environ_prefix=None
    )
    AWS_S3_SECRET_ACCESS_KEY = values.Value(
        environ_name="AWS_S3_SECRET_ACCESS_KEY", environ_prefix=None
    )
    AWS_S3_REGION_NAME = values.Value(
        environ_name="AWS_S3_REGION_NAME", environ_prefix=None
    )
    AWS_STORAGE_BUCKET_NAME = values.Value(
        "main-media-storage",
        environ_name="AWS_STORAGE_BUCKET_NAME",
        environ_prefix=None,
    )

    RESANA_S3_ENDPOINT_URL = values.Value(
        environ_name="RESANA_S3_ENDPOINT_URL", environ_prefix=None
    )
    RESANA_S3_ACCESS_KEY_ID = values.Value(
        environ_name="RESANA_S3_ACCESS_KEY_ID", environ_prefix=None
    )
    RESANA_S3_SECRET_ACCESS_KEY = values.Value(
        environ_name="RESANA_S3_SECRET_ACCESS_KEY", environ_prefix=None
    )
    RESANA_AUTH_ENDPOINT = values.Value(
        environ_name="RESANA_AUTH_ENDPOINT", environ_prefix=None
    )
    RESANA_AUTH_USER = values.Value(
        environ_name="RESANA_AUTH_USER", environ_prefix=None
    )
    RESANA_AUTH_PASSWORD = values.Value(
        environ_name="RESANA_AUTH_PASSWORD", environ_prefix=None
    )
    RESANA_API_ENDPOINT = values.Value(
        environ_name="RESANA_API_ENDPOINT", environ_prefix=None
    )
    RESANA_WEB_ENDPOINT = values.Value(
        environ_name="RESANA_WEB_ENDPOINT", environ_prefix=None
    )
    RESANA_ALT_API_ENDPOINT = values.Value(
        environ_name="RESANA_ALT_API_ENDPOINT", environ_prefix=None
    )
    RESANA_KEYCLOAK_ENDPOINT = values.Value(
        environ_name="RESANA_KEYCLOAK_ENDPOINT", environ_prefix=None
    )
    RESANA_MIGRATOR_CLIENT_ID = values.Value(
        "resana-migrator", environ_name="RESANA_MIGRATOR_CLIENT_ID", environ_prefix=None
    )
    RESANA_MIGRATOR_CLIENT_SECRET = values.Value(
        environ_name="RESANA_MIGRATOR_CLIENT_SECRET", environ_prefix=None
    )
    RESANA_MIGRATOR_REDIRECT_URI = values.Value(
        environ_name="RESANA_MIGRATOR_REDIRECT_URI", environ_prefix=None
    )
    RESANA_OTP_CHALLENGE_TTL = values.IntegerValue(
        120, environ_name="RESANA_OTP_CHALLENGE_TTL", environ_prefix=None
    )
    RESANA_S3_BUCKET = values.Value(
        environ_name="RESANA_S3_BUCKET", environ_prefix=None
    )
    RESANA_S3_REGION = values.Value(
        environ_name="RESANA_S3_REGION", environ_prefix=None
    )
    RESANA_DEFAULT_ORGANIZATION = values.Value(
        environ_name="RESANA_DEFAULT_ORGANIZATION", environ_prefix=None
    )

    S3_VERSIONS_PAGE_SIZE = 50

    # Source and destination backends
    SOURCE_BACKEND = values.Value(
        "core.sources.osmose.backend.OsmoseSourceBackend",
        environ_name="SOURCE_BACKEND",
        environ_prefix=None,
    )
    DESTINATION_BACKENDS = values.ListValue(
        [
            "core.destinations.archive.backend.ArchiveDestinationBackend",
            "core.destinations.resana.backend.ResanaDestinationBackend",
            "core.destinations.drive.backend.DriveDestinationBackend",
        ],
        environ_name="DESTINATION_BACKENDS",
        environ_prefix=None,
    )
    EXTRA_API_URL_MODULES = values.ListValue(
        [],
        environ_name="EXTRA_API_URL_MODULES",
        environ_prefix=None,
    )
    # 0 = unlimited. When > 0, migrations only download the first N files per
    # workspace (source structure fetch is unaffected, only file downloads are capped).
    MIGRATION_FILE_LIMIT_PER_WORKSPACE = values.IntegerValue(
        0,
        environ_name="MIGRATION_FILE_LIMIT_PER_WORKSPACE",
        environ_prefix=None,
    )

    # Filesystem source backend
    FILESYSTEM_SOURCE_ROOT = values.Value(
        environ_name="FILESYSTEM_SOURCE_ROOT", environ_prefix=None, default="/demo-data"
    )

    # La Suite Drive
    DRIVE_API_BASE_URL = values.Value(
        environ_name="DRIVE_API_BASE_URL", environ_prefix=None, default=""
    )
    DRIVE_OIDC_TOKEN_ENDPOINT = values.Value(
        environ_name="DRIVE_OIDC_TOKEN_ENDPOINT", environ_prefix=None, default=""
    )
    DRIVE_OIDC_CLIENT_ID = values.Value(
        environ_name="DRIVE_OIDC_CLIENT_ID", environ_prefix=None, default=""
    )
    DRIVE_OIDC_CLIENT_SECRET = values.Value(
        environ_name="DRIVE_OIDC_CLIENT_SECRET", environ_prefix=None, default=""
    )
    # "service_account": client_credentials grant via /external_api/v1.0/ (default)
    # "user_token": authenticated user's ProConnect token via /api/v1.0/
    DRIVE_AUTH_MODE = values.Value(
        "service_account", environ_name="DRIVE_AUTH_MODE", environ_prefix=None
    )
    # Set to False to skip sharing migrated files with workspace members.
    # Members will then manage permissions manually in Drive.
    DRIVE_SHARE_MEMBERS = values.BooleanValue(
        True, environ_name="DRIVE_SHARE_MEMBERS", environ_prefix=None
    )
    # Retry tuning for transient network errors on Drive API/S3 calls.
    DRIVE_RETRY_MAX_ATTEMPTS = values.IntegerValue(
        3, environ_name="DRIVE_RETRY_MAX_ATTEMPTS", environ_prefix=None
    )
    DRIVE_RETRY_WAIT_MULTIPLIER = values.IntegerValue(
        2, environ_name="DRIVE_RETRY_WAIT_MULTIPLIER", environ_prefix=None
    )
    DRIVE_RETRY_WAIT_MIN = values.IntegerValue(
        2, environ_name="DRIVE_RETRY_WAIT_MIN", environ_prefix=None
    )
    # Fernet key (URL-safe base64, 32 bytes) used to encrypt OIDC tokens at rest.
    # Generate with: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
    OIDC_TOKENS_ENCRYPTION_KEY = values.Value(
        environ_name="OIDC_TOKENS_ENCRYPTION_KEY", environ_prefix=None
    )

    # Osmose
    OSMOSE_PKI_RSA_PRIVATE_KEY = values.Value(
        environ_name="OSMOSE_PKI_RSA_PRIVATE_KEY", environ_prefix=None
    )
    OSMOSE_PKI_RSA_PRIVATE_KEY_PASSPHRASE = values.Value(
        environ_name="OSMOSE_PKI_RSA_PRIVATE_KEY_PASSPHRASE", environ_prefix=None
    )
    OSMOSE_API_ENDPOINT = values.Value(
        environ_name="OSMOSE_API_ENDPOINT", environ_prefix=None
    )
    OSMOSE_BASE_ENDPOINT = values.Value(
        environ_name="OSMOSE_BASE_ENDPOINT", environ_prefix=None
    )
    OSMOSE_JWT_SUB = values.Value(environ_name="OSMOSE_JWT_SUB", environ_prefix=None)
    OSMOSE_JWT_ISS = values.Value(environ_name="OSMOSE_JWT_ISS", environ_prefix=None)
    OSMOSE_JWT_IP_MASK = values.Value(
        environ_name="OSMOSE_JWT_IP_MASK", environ_prefix=None
    )
    OSMOSE_BACKEND = values.Value(environ_name="OSMOSE_BACKEND", environ_prefix=None)
    OSMOSE_BACKEND_DEBUG = values.BooleanValue(
        environ_name="OSMOSE_BACKEND_DEBUG", environ_prefix=None, default=False
    )
    # Prevent from failing the entire task if file downloads gives a 404.
    OSMOSE_BACKEND_ACCEPT_404 = values.BooleanValue(
        environ_name="OSMOSE_BACKEND_ACCEPT_404", environ_prefix=None, default=False
    )
    # Retry tuning for transient network errors on Osmose file downloads.
    OSMOSE_RETRY_MAX_ATTEMPTS = values.IntegerValue(
        5, environ_name="OSMOSE_RETRY_MAX_ATTEMPTS", environ_prefix=None
    )
    OSMOSE_RETRY_WAIT_MULTIPLIER = values.IntegerValue(
        2, environ_name="OSMOSE_RETRY_WAIT_MULTIPLIER", environ_prefix=None
    )
    OSMOSE_RETRY_WAIT_MIN = values.IntegerValue(
        2, environ_name="OSMOSE_RETRY_WAIT_MIN", environ_prefix=None
    )

    # Internationalization
    # https://docs.djangoproject.com/en/3.1/topics/i18n/

    # Languages
    LANGUAGE_CODE = values.Value("en-us")

    DRF_NESTED_MULTIPART_PARSER = {
        # output of parser is converted to querydict
        # if is set to False, dict python is returned
        "querydict": False,
    }

    # Careful! Languages should be ordered by priority, as this tuple is used to get
    # fallback/default languages throughout the app.
    LANGUAGES = values.SingleNestedTupleValue(
        (
            ("en-us", _("English")),
            ("fr-fr", _("French")),
        )
    )

    LOCALE_PATHS = (os.path.join(BASE_DIR, "locale"),)

    TIME_ZONE = "UTC"
    USE_I18N = True
    USE_TZ = True

    # Templates
    TEMPLATES = [
        {
            "BACKEND": "django.template.backends.django.DjangoTemplates",
            "DIRS": [os.path.join(BASE_DIR, "templates")],
            "OPTIONS": {
                "context_processors": [
                    "django.contrib.auth.context_processors.auth",
                    "django.contrib.messages.context_processors.messages",
                    "django.template.context_processors.csrf",
                    "django.template.context_processors.debug",
                    "django.template.context_processors.i18n",
                    "django.template.context_processors.media",
                    "django.template.context_processors.request",
                    "django.template.context_processors.tz",
                ],
                "loaders": [
                    "django.template.loaders.filesystem.Loader",
                    "django.template.loaders.app_directories.Loader",
                ],
            },
        },
    ]

    MIDDLEWARE = [
        "django.middleware.security.SecurityMiddleware",
        "whitenoise.middleware.WhiteNoiseMiddleware",
        "django.contrib.sessions.middleware.SessionMiddleware",
        "django.middleware.locale.LocaleMiddleware",
        "django.middleware.clickjacking.XFrameOptionsMiddleware",
        "corsheaders.middleware.CorsMiddleware",
        "django.middleware.common.CommonMiddleware",
        "django.middleware.csrf.CsrfViewMiddleware",
        "django.contrib.auth.middleware.AuthenticationMiddleware",
        "django.contrib.messages.middleware.MessageMiddleware",
        "dockerflow.django.middleware.DockerflowMiddleware",
        "hijack.middleware.HijackUserMiddleware",
    ]

    AUTHENTICATION_BACKENDS = [
        "django.contrib.auth.backends.ModelBackend",
        "core.authentication.backends.OIDCAuthenticationBackend",
    ]

    # Django applications from the highest priority to the lowest
    INSTALLED_APPS = [
        # Makes the superuser command not overridden by auth.
        "demo",
        # Django
        "django.contrib.admin",
        "django.contrib.auth",
        "django.contrib.contenttypes",
        "django.contrib.postgres",
        "django.contrib.sessions",
        "django.contrib.sites",
        "django.contrib.messages",
        "django.contrib.staticfiles",
        # app
        "core",
        # Third party apps
        "drf_spectacular",
        "corsheaders",
        "dockerflow.django",
        "rest_framework",
        "django_filters",
        "parler",
        # Third Party apps
        "hijack",
        "hijack.contrib.admin",
        # OIDC third party
        "mozilla_django_oidc",
        "django_celery_results",
    ]

    # Cache
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": values.Value(
                "redis://redis:6379/1",
                environ_name="REDIS_URL",
                environ_prefix=None,
            ),
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
        },
    }

    REST_FRAMEWORK = {
        "DEFAULT_AUTHENTICATION_CLASSES": (
            "mozilla_django_oidc.contrib.drf.OIDCAuthentication",
            "rest_framework.authentication.SessionAuthentication",
        ),
        "DEFAULT_PARSER_CLASSES": [
            "rest_framework.parsers.JSONParser",
            "nested_multipart_parser.drf.DrfNestedParser",
        ],
        "EXCEPTION_HANDLER": "core.api.exception_handler",
        "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
        "PAGE_SIZE": 1000,
        "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.URLPathVersioning",
        "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    }

    SPECTACULAR_SETTINGS = {
        "TITLE": "Impress API",
        "DESCRIPTION": "This is the API schema.",
        "VERSION": "1.0.0",
        "SERVE_INCLUDE_SCHEMA": False,
        "ENABLE_DJANGO_DEPLOY_CHECK": values.BooleanValue(
            default=False,
            environ_name="SPECTACULAR_SETTINGS_ENABLE_DJANGO_DEPLOY_CHECK",
        ),
        "COMPONENT_SPLIT_REQUEST": True,
        # OTHER SETTINGS
        "SWAGGER_UI_DIST": "SIDECAR",  # shorthand to use the sidecar instead
        "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
        "REDOC_DIST": "SIDECAR",
    }

    # Mail
    EMAIL_BACKEND = values.Value("django.core.mail.backends.smtp.EmailBackend")
    EMAIL_HOST = values.Value(None)
    EMAIL_HOST_USER = values.Value(None)
    EMAIL_HOST_PASSWORD = values.Value(None)
    EMAIL_PORT = values.PositiveIntegerValue(None)
    EMAIL_USE_TLS = values.BooleanValue(False)
    EMAIL_USE_SSL = values.BooleanValue(False)
    EMAIL_FROM = values.Value("from@example.com")

    AUTH_USER_MODEL = "core.User"
    INVITATION_VALIDITY_DURATION = 604800  # 7 days, in seconds

    # CORS
    CORS_ALLOW_CREDENTIALS = True
    CORS_ALLOW_ALL_ORIGINS = values.BooleanValue(True)
    CORS_ALLOWED_ORIGINS = values.ListValue([])
    CORS_ALLOWED_ORIGIN_REGEXES = values.ListValue([])

    # Sentry
    SENTRY_DSN = values.Value(environ_name="SENTRY_DSN", environ_prefix=None)

    # Easy thumbnails
    THUMBNAIL_EXTENSION = "webp"
    THUMBNAIL_TRANSPARENCY_EXTENSION = "webp"
    THUMBNAIL_ALIASES = {}

    # Celery
    CELERY_BROKER_URL = values.Value(
        "redis://redis:6379/0",
        environ_name="REDIS_URL",
        environ_prefix=None,
    )
    CELERY_BROKER_TRANSPORT_OPTIONS = values.DictValue({})
    CELERY_RESULT_BACKEND = "django-db"
    CELERY_CACHE_BACKEND = "django-cache"
    CELERY_TASK_SERIALIZER = "json"
    CELERY_RESULT_SERIALIZER = "json"
    CELERY_ACCEPT_CONTENT = ["json"]
    CELERY_RESULT_EXTENDED = True
    CELERY_TRACK_STARTED = True

    # Session
    SESSION_ENGINE = "django.contrib.sessions.backends.cache"
    SESSION_CACHE_ALIAS = "default"
    SESSION_COOKIE_AGE = 60 * 60 * 12

    # OIDC - Authorization Code Flow
    OIDC_CREATE_USER = values.BooleanValue(
        default=True,
        environ_name="OIDC_CREATE_USER",
    )
    OIDC_RP_SIGN_ALGO = values.Value(
        "RS256", environ_name="OIDC_RP_SIGN_ALGO", environ_prefix=None
    )
    OIDC_RP_CLIENT_ID = values.Value(
        "main", environ_name="OIDC_RP_CLIENT_ID", environ_prefix=None
    )
    OIDC_RP_CLIENT_SECRET = values.Value(
        None,
        environ_name="OIDC_RP_CLIENT_SECRET",
        environ_prefix=None,
    )
    OIDC_OP_JWKS_ENDPOINT = values.Value(
        environ_name="OIDC_OP_JWKS_ENDPOINT", environ_prefix=None
    )
    OIDC_OP_AUTHORIZATION_ENDPOINT = values.Value(
        environ_name="OIDC_OP_AUTHORIZATION_ENDPOINT", environ_prefix=None
    )
    OIDC_OP_TOKEN_ENDPOINT = values.Value(
        None, environ_name="OIDC_OP_TOKEN_ENDPOINT", environ_prefix=None
    )
    OIDC_OP_USER_ENDPOINT = values.Value(
        None, environ_name="OIDC_OP_USER_ENDPOINT", environ_prefix=None
    )
    OIDC_OP_LOGOUT_ENDPOINT = values.Value(
        None, environ_name="OIDC_OP_LOGOUT_ENDPOINT", environ_prefix=None
    )
    OIDC_AUTH_REQUEST_EXTRA_PARAMS = values.DictValue(
        {}, environ_name="OIDC_AUTH_REQUEST_EXTRA_PARAMS", environ_prefix=None
    )
    OIDC_RP_SCOPES = values.Value(
        "openid email", environ_name="OIDC_RP_SCOPES", environ_prefix=None
    )
    LOGIN_REDIRECT_URL = values.Value(
        None, environ_name="LOGIN_REDIRECT_URL", environ_prefix=None
    )
    LOGIN_REDIRECT_URL_FAILURE = values.Value(
        None, environ_name="LOGIN_REDIRECT_URL_FAILURE", environ_prefix=None
    )
    # Frontend path users with an account pending admin validation (restricted
    # mode, is_active=False) are redirected to, appended to LOGIN_REDIRECT_URL_FAILURE's
    # domain instead of redirecting to its path (the logged-out homepage).
    LOGIN_REDIRECT_PENDING_VALIDATION_PATH = values.Value(
        "/account-pending",
        environ_name="LOGIN_REDIRECT_PENDING_VALIDATION_PATH",
        environ_prefix=None,
    )
    OIDC_CALLBACK_CLASS = "core.authentication.views.OIDCAuthenticationCallbackView"
    LOGOUT_REDIRECT_URL = values.Value(
        None, environ_name="LOGOUT_REDIRECT_URL", environ_prefix=None
    )
    OIDC_USE_NONCE = values.BooleanValue(
        default=True, environ_name="OIDC_USE_NONCE", environ_prefix=None
    )
    OIDC_REDIRECT_REQUIRE_HTTPS = values.BooleanValue(
        default=False, environ_name="OIDC_REDIRECT_REQUIRE_HTTPS", environ_prefix=None
    )
    OIDC_REDIRECT_ALLOWED_HOSTS = values.ListValue(
        default=[], environ_name="OIDC_REDIRECT_ALLOWED_HOSTS", environ_prefix=None
    )
    OIDC_STORE_ID_TOKEN = values.BooleanValue(
        default=True, environ_name="OIDC_STORE_ID_TOKEN", environ_prefix=None
    )
    ALLOW_LOGOUT_GET_METHOD = values.BooleanValue(
        default=True, environ_name="ALLOW_LOGOUT_GET_METHOD", environ_prefix=None
    )

    INTERNAL_IPS = [
        "127.0.0.1",
    ]

    DEBUG_TOOLBAR_CONFIG = {
        "SHOW_TOOLBAR_CALLBACK": lambda request: True,
    }

    # pylint: disable=invalid-name
    @property
    def ENVIRONMENT(self):
        """Environment in which the application is launched."""
        return self.__class__.__name__.lower()

    # pylint: disable=invalid-name
    @property
    def RELEASE(self):
        """
        Return the release information.

        Delegate to the module function to enable easier testing.
        """
        return get_release()

    # pylint: disable=invalid-name
    @property
    def PARLER_LANGUAGES(self):
        """
        Return languages for Parler computed from the LANGUAGES and LANGUAGE_CODE settings.
        """
        return {
            self.SITE_ID: tuple({"code": code} for code, _name in self.LANGUAGES),
            "default": {
                "fallbacks": [self.LANGUAGE_CODE],
                "hide_untranslated": False,
            },
        }

    @classmethod
    def post_setup(cls):
        """Post setup configuration.
        This is the place where you can configure settings that require other
        settings to be loaded.
        """
        super().post_setup()

        # The SENTRY_DSN setting should be available to activate sentry for an environment
        if cls.SENTRY_DSN is not None:
            sentry_sdk.init(
                dsn=cls.SENTRY_DSN,
                environment=cls.__name__.lower(),
                release=get_release(),
                integrations=[DjangoIntegration()],
            )

            # Add the application name to the Sentry scope
            scope = sentry_sdk.get_global_scope()
            scope.set_tag("application", "backend")

            # Ignore the logs added by the DockerflowMiddleware
            ignore_logger("request.summary")


class Build(Base):
    """Settings used when the application is built.

    This environment should not be used to run the application. Just to build it with non-blocking
    settings.
    """

    SECRET_KEY = values.Value("DummyKey")
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": values.Value(
                "whitenoise.storage.CompressedManifestStaticFilesStorage",
                environ_name="STORAGES_STATICFILES_BACKEND",
            ),
        },
    }


class Development(Base):
    """
    Development environment settings

    We set DEBUG to True and configure the server to respond from all hosts.
    """

    ALLOWED_HOSTS = ["*"]
    CORS_ALLOW_ALL_ORIGINS = True
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:8072",
        "http://localhost:3000",
        "http://localhost:3010",
    ]
    DEBUG = True

    SESSION_COOKIE_NAME = "main_sessionid"

    USE_SWAGGER = True

    SESSION_COOKIE_SECURE = False
    SOCIAL_AUTH_REDIRECT_IS_HTTPS = True

    def __init__(self):
        # pylint: disable=invalid-name
        self.MIDDLEWARE += ["debug_toolbar.middleware.DebugToolbarMiddleware"]
        self.INSTALLED_APPS += [
            "django_extensions",
            "drf_spectacular_sidecar",
            "debug_toolbar",
        ]


class Test(Base):
    """Test environment settings"""

    EXTRA_API_URL_MODULES = ["core.sources.resana.urls"]

    LOGGING = values.DictValue(
        {
            "version": 1,
            "disable_existing_loggers": False,
            "handlers": {
                "console": {
                    "class": "logging.StreamHandler",
                },
            },
            "loggers": {
                "main": {
                    "handlers": ["console"],
                    "level": "DEBUG",
                },
            },
        }
    )
    PASSWORD_HASHERS = [
        "django.contrib.auth.hashers.MD5PasswordHasher",
    ]
    USE_SWAGGER = True

    def __init__(self):
        # pylint: disable=invalid-name
        self.INSTALLED_APPS += ["drf_spectacular_sidecar"]


class ContinuousIntegration(Test):
    """
    Continuous Integration environment settings

    nota bene: it should inherit from the Test environment.
    """


class Production(Base):
    """
    Production environment settings

    You must define the ALLOWED_HOSTS environment variable in Production
    configuration (and derived configurations):
    ALLOWED_HOSTS=["foo.com", "foo.fr"]
    """

    # Security
    # Add allowed host from environment variables.
    # The machine hostname is added by default,
    # it makes the application pingable by a load balancer on the same machine by example
    ALLOWED_HOSTS = [
        *values.ListValue([], environ_name="ALLOWED_HOSTS"),
        gethostbyname(gethostname()),
    ]
    CSRF_TRUSTED_ORIGINS = values.ListValue([])
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

    # SECURE_PROXY_SSL_HEADER allows to fix the scheme in Django's HttpRequest
    # object when your application is behind a reverse proxy.
    #
    # Keep this SECURE_PROXY_SSL_HEADER configuration only if :
    # - your Django app is behind a proxy.
    # - your proxy strips the X-Forwarded-Proto header from all incoming requests
    # - Your proxy sets the X-Forwarded-Proto header and sends it to Django
    #
    # In other cases, you should comment the following line to avoid security issues.
    # SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # Modern browsers require to have the `secure` attribute on cookies with `Samesite=none`
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 60
    SECURE_HSTS_PRELOAD = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_SSL_REDIRECT = True
    SECURE_REDIRECT_EXEMPT = [
        "^__lbheartbeat__",
        "^__heartbeat__",
    ]

    # Privacy
    SECURE_REFERRER_POLICY = "same-origin"

    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": values.Value(
                "redis://redis:6379/1",
                environ_name="REDIS_URL",
                environ_prefix=None,
            ),
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
        },
    }

    DEBUG = False


class Feature(Production):
    """
    Feature environment settings

    nota bene: it should inherit from the Production environment.
    """


class Staging(Production):
    """
    Staging environment settings

    nota bene: it should inherit from the Production environment.
    """

    DEBUG = True


class PreProduction(Production):
    """
    Pre-production environment settings

    nota bene: it should inherit from the Production environment.
    """


class Demo(Production):
    """
    Demonstration environment settings

    nota bene: it should inherit from the Production environment.
    """

    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
