apiVersion: v1
kind: Secret
metadata:
  name: backend
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
stringData:
  DJANGO_SUPERUSER_EMAIL: {{ .Values.djangoSuperUserEmail }}
  DJANGO_SUPERUSER_PASSWORD: {{ .Values.djangoSuperUserPass }}
  OIDC_RP_CLIENT_ID: {{ .Values.oidc.clientId }}
  OIDC_RP_CLIENT_SECRET: {{ .Values.oidc.clientSecret }}
  DJANGO_SECRET_KEY: {{ .Values.djangoSecretKey }}
  OSMOSE_PKI_RSA_PRIVATE_KEY: |
{{ .Values.osmose_pki_rsa_private_key | indent 4 }}
  OSMOSE_PKI_RSA_PRIVATE_KEY_PASSPHRASE: {{ .Values.osmose_pki_rsa_private_key_passphrase }}
  OSMOSE_JWT_SUB: {{ .Values.osmose_jwt_sub }}
  OSMOSE_JWT_ISS: {{ .Values.osmose_jwt_iss }}
  OSMOSE_API_ENDPOINT: {{ .Values.osmose_api_endpoint }}
  OSMOSE_BASE_ENDPOINT: {{ .Values.osmose_base_endpoint }}
---
{{ include "template.secret.dockerconfigjson" (dict "fullname" (include "template.fullname" .) "imageCredentials" .Values.image.credentials) }}
