apiVersion: v1
kind: Secret
metadata:
  name: backend
  namespace: {{ .Release.Namespace | quote }}
stringData:
  DJANGO_SUPERUSER_EMAIL: {{ .Values.djangoSuperUserEmail }}
  DJANGO_SUPERUSER_PASSWORD: {{ .Values.djangoSuperUserPass }}
  OIDC_RP_CLIENT_ID: {{ .Values.oidc.clientId }}
  OIDC_RP_CLIENT_SECRET: {{ .Values.oidc.clientSecret }}
  DJANGO_SECRET_KEY: {{ .Values.djangoSecretKey }}
  OIDC_RP_CLIENT_ID: {{ .Values.oidc.clientId }}
  OIDC_RP_CLIENT_SECRET: {{ .Values.oidc.clientSecret }}
---
{{ include "template.secret.dockerconfigjson" (dict "fullname" (include "template.fullname" .) "imageCredentials" .Values.image.credentials) }}
