# Generated by Django 5.0.3 on 2024-07-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_workspace_alter_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='workspaces',
            field=models.ManyToManyField(to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices="(('en-us', 'English'), ('fr-fr', 'French'))", default='en-us', help_text='The language in which the user wants to see the interface.', max_length=10, verbose_name='language'),
        ),
    ]
