# Generated by Django 5.0.3 on 2024-07-02 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_workspaces_alter_user_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrataskinfo',
            name='workspace_id',
        ),
        migrations.AddField(
            model_name='extrataskinfo',
            name='workspace',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.workspace'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices="(('en-us', 'English'), ('fr-fr', 'French'))", default='en-us', help_text='The language in which the user wants to see the interface.', max_length=10, verbose_name='language'),
        ),
    ]
