# Generated by Django 5.0.3 on 2024-07-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_extrataskinfo_workspace_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='status_archive',
            field=models.CharField(choices=[('NONE', 'None'), ('PENDING', 'Pending'), ('FAILURE', 'Failure'), ('SUCCESS', 'Success')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='workspace',
            name='status_resana',
            field=models.CharField(choices=[('NONE', 'None'), ('PENDING', 'Pending'), ('FAILURE', 'Failure'), ('SUCCESS', 'Success')], default='NONE', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices="(('en-us', 'English'), ('fr-fr', 'French'))", default='en-us', help_text='The language in which the user wants to see the interface.', max_length=10, verbose_name='language'),
        ),
    ]
