# Generated by Django 5.0.3 on 2024-10-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_workspace_status_archive_workspace_status_resana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='resana_id',
            field=models.CharField(help_text='id of the Resana workspace', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices="(('en-us', 'English'), ('fr-fr', 'French'))", default='en-us', help_text='The language in which the user wants to see the interface.', max_length=10, verbose_name='language'),
        ),
    ]
