# Generated by Django 5.0.3 on 2024-10-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_workspace_resana_id_alter_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='job_id',
            field=models.CharField(blank=True, help_text='id of the Resana job', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices="(('en-us', 'English'), ('fr-fr', 'French'))", default='en-us', help_text='The language in which the user wants to see the interface.', max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='resana_id',
            field=models.CharField(blank=True, help_text='id of the Resana workspace', null=True),
        ),
    ]
