# Generated by Django 5.0.3 on 2024-10-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_workspace_job_id_alter_user_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspace',
            old_name='job_id',
            new_name='resana_job_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices="(('en-us', 'English'), ('fr-fr', 'French'))", default='en-us', help_text='The language in which the user wants to see the interface.', max_length=10, verbose_name='language'),
        ),
    ]
