# Generated by Django 5.0.3 on 2024-10-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_extrataskinfo_user_alter_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='archive_path',
            field=models.CharField(blank=True, help_text='path of the archive on s3', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices="(('en-us', 'English'), ('fr-fr', 'French'))", default='en-us', help_text='The language in which the user wants to see the interface.', max_length=10, verbose_name='language'),
        ),
    ]
