# Generated by Django 5.0.3 on 2024-10-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_featureflag_alter_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflag',
            name='name',
            field=models.CharField(choices=[('allow-new-tasks', 'Allow New Tasks')], max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices="(('en-us', 'English'), ('fr-fr', 'French'))", default='en-us', help_text='The language in which the user wants to see the interface.', max_length=10, verbose_name='language'),
        ),
    ]
