# Generated by Django 5.1.3 on 2025-01-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_resanaemailmapping_domain_alter_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='resana_files_error',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='resana_files_success',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices="(('en-us', 'English'), ('fr-fr', 'French'))", default='en-us', help_text='The language in which the user wants to see the interface.', max_length=10, verbose_name='language'),
        ),
    ]
