# Generated by Django 5.1.7 on 2026-03-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_workspace_resana_files_error_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='archive_path',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='osmose_id',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='resana_files_error',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='resana_files_success',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='resana_id',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='resana_job_id',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='status_archive',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='status_resana',
        ),
        migrations.AddField(
            model_name='workspace',
            name='destination_metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='workspace',
            name='destination_statuses',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='workspace',
            name='source_id',
            field=models.CharField(default='', help_text='id of the workspace on the source platform', unique=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='source_type',
            field=models.CharField(default='', help_text="source backend type, e.g. 'osmose', 'filesystem'"),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='name',
            field=models.CharField(choices=[('allow-new-tasks', 'Allow New Tasks'), ('read-only-mode', 'Read Only Mode')], max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices="(('en-us', 'English'), ('fr-fr', 'French'))", default='en-us', help_text='The language in which the user wants to see the interface.', max_length=10, verbose_name='language'),
        ),
    ]
