# Generated by Django 5.1.7 on 2026-04-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='members',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices="(('en-us', 'English'), ('fr-fr', 'French'))", default='en-us', help_text='The language in which the user wants to see the interface.', max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='destination_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='destination_statuses',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
