# Generated by Django 5.1.7 on 2026-04-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_workspace_members_alter_user_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oidc_access_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='oidc_refresh_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='oidc_token_expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiry datetime of the stored OIDC access token.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices="(('en-us', 'English'), ('fr-fr', 'French'))", default='en-us', help_text='The language in which the user wants to see the interface.', max_length=10, verbose_name='language'),
        ),
    ]
