# Generated by Django 5.1.7 on 2026-05-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_user_oidc_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resana_access_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='resana_refresh_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='resana_token_expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiry datetime of the stored Resana access token (3h lifetime).', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices="(('en-us', 'English'), ('fr-fr', 'French'))", default='en-us', help_text='The language in which the user wants to see the interface.', max_length=10, verbose_name='language'),
        ),
    ]
