# Generated by Django 5.1.7 on 2026-07-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_user_resana_access_token_user_resana_refresh_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflag',
            name='name',
            field=models.CharField(choices=[('allow-new-tasks', 'Allow New Tasks'), ('read-only-mode', 'Read Only Mode'), ('auto-validate-new-users', 'Auto Validate New Users')], max_length=32),
        ),
    ]
