# Generated by Django 5.2.16 on 2026-08-06 13:08

from django.db import migrations, models


def clear_legacy_resana_tokens(apps, schema_editor):
    """Tokens issued by the old Auth Service flow are unusable with the bridge flow."""
    User = apps.get_model("core", "User")
    User.objects.exclude(resana_access_token="", resana_refresh_token="").update(
        resana_access_token="",
        resana_refresh_token="",
        resana_token_expires_at=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_workspace_is_truncated_alter_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resana_csrf_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='resana_session_id',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='resana_token_expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiry datetime of the stored Resana access token.', null=True),
        ),
        migrations.RunPython(clear_legacy_resana_tokens, migrations.RunPython.noop),
    ]
