# Generated by Django 5.2.16 on 2026-09-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_workspace_download_errors_alter_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='source_lock_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
