# Generated by Django 5.2.16 on 2026-09-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_workspace_download_errors_alter_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrataskinfo',
            name='integrity_check_passed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extrataskinfo',
            name='integrity_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='workspace',
            name='is_file_integrity_tracked',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='name',
            field=models.CharField(choices=[('allow-new-tasks', 'Allow New Tasks'), ('read-only-mode', 'Read Only Mode'), ('auto-validate-new-users', 'Auto Validate New Users'), ('file-integrity-tracking', 'File Integrity Tracking')], max_length=32),
        ),
    ]
