# Generated by Django 5.2.16 on 2026-10-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_workspace_source_lock_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='upload_errors',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
