name: Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

permissions:
  contents: read

jobs:

  install-front:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup node and yarn 
        uses: ./.github/actions/yarn-setup
        with:
          node-version: "20.x"
          lock-file-path: 'src/frontend/**/yarn.lock'
          node-module-path: 'src/frontend/**/node_modules'
          working-directory: src/frontend
          cache: true 

  build-front:
    runs-on: ubuntu-latest
    needs: install-front
    defaults:
      run:
        working-directory: src/frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup node and yarn 
        uses: ./.github/actions/yarn-setup
        with:
          node-version: "20.x"
          lock-file-path: 'src/frontend/**/yarn.lock'
          node-module-path: 'src/frontend/**/node_modules'
          working-directory: src/frontend

      - name: Build CI App
        run: yarn ci:build

      - name: Cache build frontend
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: src/frontend/apps/main/out/
          key: build-front-${{ github.run_id }}

  test-front:
    runs-on: ubuntu-latest
    needs: install-front
    defaults:
      run:
        working-directory: src/frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup node and yarn 
        uses: ./.github/actions/yarn-setup
        with:
          node-version: "20.x"
          lock-file-path: 'src/frontend/**/yarn.lock'
          node-module-path: 'src/frontend/**/node_modules'
          working-directory: src/frontend

      - name: Test App
        run: yarn app:test

  lint-front:
    runs-on: ubuntu-latest
    needs: install-front
    defaults:
      run:
        working-directory: src/frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup node and yarn 
        uses: ./.github/actions/yarn-setup
        with:
          node-version: "20.x"
          lock-file-path: 'src/frontend/**/yarn.lock'
          node-module-path: 'src/frontend/**/node_modules'
          working-directory: src/frontend

      - name: Check linting
        run: yarn lint
