name: Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

permissions:
  contents: read

jobs:

  install-front:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: src/frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Setup node and yarn 
        uses: ./.github/actions/yarn-setup
        with:
          node-version: "20.x"
          lock-file-path: 'src/frontend/**/yarn.lock'
          node-module-path: 'src/frontend/**/node_modules'
          working-directory: src/frontend
          cache: true 

  build-front:
    runs-on: self-hosted
    needs: install-front
    defaults:
      run:
        working-directory: src/frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Setup node and yarn 
        uses: ./.github/actions/yarn-setup
        with:
          node-version: "20.x"
          lock-file-path: 'src/frontend/**/yarn.lock'
          node-module-path: 'src/frontend/**/node_modules'
          working-directory: src/frontend

      - name: Build CI App
        run: yarn ci:build

      - name: Cache build frontend
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: src/frontend/apps/main/out/
          key: build-front-${{ github.run_id }}

  test-front:
    runs-on: self-hosted
    needs: install-front
    defaults:
      run:
        working-directory: src/frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Setup node and yarn 
        uses: ./.github/actions/yarn-setup
        with:
          node-version: "20.x"
          lock-file-path: 'src/frontend/**/yarn.lock'
          node-module-path: 'src/frontend/**/node_modules'
          working-directory: src/frontend

      - name: Test App
        run: yarn app:test

  lint-front:
    runs-on: self-hosted
    needs: install-front
    defaults:
      run:
        working-directory: src/frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Setup node and yarn 
        uses: ./.github/actions/yarn-setup
        with:
          node-version: "20.x"
          lock-file-path: 'src/frontend/**/yarn.lock'
          node-module-path: 'src/frontend/**/node_modules'
          working-directory: src/frontend

      - name: Check linting
        run: yarn lint
